//go:build ignore

package main // generate.go

import (
	"fmt"
	"log"
	"os"
)

func main() {
	src, err := os.ReadFile("main.go")
	if err != nil {
		log.Fatal(err)
	}
	output := `// Code generated by go generate; DO NOT EDIT.
package main

var src = ` + fmt.Sprintf("`%s`\r\n", string(src))

	err = os.WriteFile("source.go", []byte(output), 0666)
	if err != nil {
		log.Fatal(err)
	}
}
